using System.Text;
using Simbro.Core.State;

namespace Simbro.Core.Save;

/// <summary>
/// Writes game state in XStream's format, so the <b>original Java game can load it</b>.
/// </summary>
/// <remarks>
/// The output is hand-built rather than produced by <see cref="System.Xml.XmlWriter"/>
/// because XStream's spelling is specific and a generic writer fights it:
/// <list type="bullet">
///   <item>the header is <c>&lt;?xml version="1.0" ?&gt;</c> — with a space before <c>?&gt;</c>;</item>
///   <item>empty elements are written as <c>&lt;x&gt;&lt;/x&gt;</c>, <b>never</b> self-closed <c>&lt;x/&gt;</c>;</item>
///   <item>the root element is the fully-qualified Java class name, not the JAXB name.</item>
/// </list>
/// All three were confirmed against fixtures generated by the real game classes
/// (see <c>SAVE-FORMAT.md</c>).
///
/// <para>Deliberately preserved oddities: <c>EventManager</c> serialises its listener
/// collection's <b>private internals</b> (lock, queue, backing array). That is genuinely what the
/// shipped game writes, so <see cref="WriteEventManager"/> reproduces it instead of writing a
/// clean listener list — anything else changes the on-disk format and the Java loader rejects or
/// mis-reads it.</para>
/// </remarks>
public static class SaveFileWriter
{
    /// <summary>XStream's XML declaration, including the space before <c>?&gt;</c>.</summary>
    public const string Declaration = "<?xml version=\"1.0\" ?>";

    /// <summary>Serialise a <see cref="GameData"/> as a loadable XStream save.</summary>
    /// <param name="data">The game state to write.</param>
    /// <param name="characters">
    /// Characters to persist. Their content definition is NOT written — see
    /// <see cref="CharacterSaveState.BaseId"/> for why.
    /// </param>
    public static string WriteGameData(
        GameData data,
        IReadOnlyList<CharacterSaveState>? characters = null)
    {
        var sb = new StringBuilder();
        sb.Append(Declaration);
        sb.Append("<jasbro.game.GameData>");

        // Field order follows the legacy declaration order in jasbro.game.GameData.
        sb.Append("<day>").Append(data.Day).Append("</day>");
        sb.Append("<time>").Append(data.Time).Append("</time>");
        sb.Append("<money>").Append(data.Money).Append("</money>");

        sb.Append("<houses></houses>");

        sb.Append("<inventory><items></items></inventory>");

        WriteEventManager(sb);

        WriteCharacters(sb, characters);

        WriteDefaultPreferences(sb);

        sb.Append("<unlocks></unlocks>");

        sb.Append("</jasbro.game.GameData>");
        return sb.ToString();
    }

    private static void WriteCharacters(StringBuilder sb, IReadOnlyList<CharacterSaveState>? characters)
    {
        if (characters is null || characters.Count == 0)
        {
            sb.Append("<characters></characters>");
            return;
        }

        sb.Append("<characters>");
        foreach (var c in characters)
        {
            WriteCharacter(sb, c);
        }
        sb.Append("</characters>");
    }

    /// <summary>
    /// Write one character. Field order matches <c>Charakter</c>'s declaration order, and the
    /// fields that are null in a new character are omitted entirely — XStream omits nulls, and
    /// emitting them would not match what the game writes.
    /// </summary>
    private static void WriteCharacter(StringBuilder sb, CharacterSaveState c)
    {
        sb.Append("<jasbro.game.character.Charakter>");

        // Every Charakter extends GameObject, whose listener list serialises its internals.
        sb.Append("<listeners><copyListLock><value>false</value></copyListLock>");
        sb.Append("<queue><lock></lock><queueLength>0</queueLength></queue><list></list></listeners>");

        sb.Append("<name>").Append(Escape(c.Name)).Append("</name>");

        // Map<AttributeType, Attribute> — empty in this shape.
        sb.Append("<attributes></attributes>");

        // EnumMap<Time, PlannedActivity> and EnumSet<SpecializationType> get XStream's
        // dedicated spellings; omitting either attribute breaks a round trip.
        sb.Append("<activities class=\"enum-map\" enum-type=\"jasbro.game.world.Time\"></activities>");
        sb.Append("<specializations class=\"enum-set\" " +
                  "enum-type=\"jasbro.game.character.specialization.SpecializationType\"></specializations>");

        sb.Append("<conditions></conditions>");

        if (c.Type is { } type)
        {
            sb.Append("<type>").Append(type).Append("</type>");
        }
        if (c.Gender is { } gender)
        {
            sb.Append("<gender>").Append(gender).Append("</gender>");
        }

        sb.Append("<fame><fame>").Append(FormatDouble(c.Fame)).Append("</fame></fame>");
        sb.Append("<ownership>").Append(c.Ownership).Append("</ownership>");

        if (c.Traits.Count > 0)
        {
            // A List<Trait> writes each element named with the enum's FULLY-QUALIFIED type.
            sb.Append("<traits>");
            foreach (var t in c.Traits)
            {
                sb.Append("<jasbro.game.character.traits.Trait>").Append(t)
                  .Append("</jasbro.game.character.traits.Trait>");
            }
            sb.Append("</traits>");
        }

        sb.Append("<baseId>").Append(Escape(c.BaseId)).Append("</baseId>");
        sb.Append("<bonusPerks>").Append(c.BonusPerks).Append("</bonusPerks>");
        sb.Append("<numberTrees>").Append(c.NumberTrees).Append("</numberTrees>");

        sb.Append("</jasbro.game.character.Charakter>");
    }

    /// <summary>Java writes doubles with a trailing <c>.0</c> when whole — match it.</summary>
    private static string FormatDouble(double value) =>
        value == Math.Floor(value) && !double.IsInfinity(value)
            ? value.ToString("0.0", System.Globalization.CultureInfo.InvariantCulture)
            : value.ToString(System.Globalization.CultureInfo.InvariantCulture);

    private static string Escape(string s) => s
        .Replace("&", "&amp;")
        .Replace("<", "&lt;")
        .Replace(">", "&gt;");

    /// <summary>
    /// Reproduces <c>EventManager</c>, including the <c>WeakList</c> internals that leak into
    /// every real save. See the class remarks — this is faithful, not tidy.
    /// </summary>
    private static void WriteEventManager(StringBuilder sb)
    {
        sb.Append("<eventManager>");
        sb.Append("<listeners class=\"jasbro.WeakList\">");
        sb.Append("<copyListLock><value>false</value></copyListLock>");
        sb.Append("<queue><lock></lock><queueLength>0</queueLength></queue>");
        sb.Append("<list></list>");
        sb.Append("</listeners>");
        sb.Append("</eventManager>");
    }

    /// <summary>Default new-game preferences, matching the legacy defaults.</summary>
    private static void WriteDefaultPreferences(StringBuilder sb)
    {
        sb.Append("<defaultPreferences>");

        // Legacy defaults differ per target gender (DefaultPreferences in the decompiled source).
        sb.Append("<allowedServicesMale><allowedServicesMap></allowedServicesMap>");
        sb.Append("<serviceMales>false</serviceMales><serviceFemales>true</serviceFemales><serviceFutas>false</serviceFutas>");
        sb.Append("</allowedServicesMale>");

        sb.Append("<allowedServicesFemale><allowedServicesMap></allowedServicesMap>");
        sb.Append("<serviceMales>true</serviceMales><serviceFemales>true</serviceFemales><serviceFutas>true</serviceFutas>");
        sb.Append("</allowedServicesFemale>");

        sb.Append("<allowedServicesFuta><allowedServicesMap></allowedServicesMap>");
        sb.Append("<serviceMales>true</serviceMales><serviceFemales>true</serviceFemales><serviceFutas>true</serviceFutas>");
        sb.Append("</allowedServicesFuta>");

        sb.Append("</defaultPreferences>");
    }
}
