using System.Xml.Linq;

namespace Simbro.Core.Save;

/// <summary>
/// A node in an XStream-serialised document.
/// </summary>
/// <remarks>
/// XStream does not write a schema: an element's <b>name is its type</b>. A field whose declared
/// type matches exactly is written as a bare element (<c>&lt;money&gt;1234&lt;/money&gt;</c>), while
/// a polymorphic or interface-typed field carries the concrete class name either as the element
/// name itself (<c>&lt;jasbro.game.GameData&gt;</c>) or in a <c>class</c> attribute
/// (<c>&lt;listeners class="jasbro.WeakList"&gt;</c>). Distinguishing these cases is the whole game.
/// </remarks>
public sealed class XStreamNode
{
    /// <summary>The element's local name — a field name, or a fully-qualified class name.</summary>
    public required string Name { get; init; }

    public Dictionary<string, string> Attributes { get; } = new(StringComparer.Ordinal);

    public List<XStreamNode> Children { get; } = new();

    /// <summary>Leaf text, or null if this element has child elements.</summary>
    public string? Text { get; set; }

    /// <summary>Enclosing node, or null for the root. Set during parsing.</summary>
    public XStreamNode? Parent { get; internal set; }

    /// <summary>
    /// The concrete type this element represents, or null when the element is a plain field
    /// whose type was known from the field declaration.
    /// </summary>
    /// <remarks>
    /// Two spellings carry a type: a dotted element name, and a <c>class</c> attribute.
    /// </remarks>
    public string? ExplicitType
    {
        get
        {
            var cls = Attributes.GetValueOrDefault("class");
            return cls ?? (Name.Contains('.') ? Name : null);
        }
    }

    /// <summary>The raw <c>reference</c> attribute, or null when this node is an inline object.</summary>
    public string? ReferencePath => Attributes.GetValueOrDefault("reference");

    /// <summary>True when this is an XStream reference rather than an inline object.</summary>
    public bool IsReference => ReferencePath is not null;

    public XStreamNode? Child(string name) =>
        Children.FirstOrDefault(c => c.Name == name);

    public IEnumerable<XStreamNode> ChildrenNamed(string name) =>
        Children.Where(c => c.Name == name);

    public string? ChildText(string name) => Child(name)?.Text;

    public int? ChildInt(string name)
    {
        var t = ChildText(name);
        return t is not null && int.TryParse(t, out var v) ? v : null;
    }

    public long? ChildLong(string name)
    {
        var t = ChildText(name);
        return t is not null && long.TryParse(t, out var v) ? v : null;
    }

    public override string ToString() =>
        $"<{Name}{(ExplicitType is null ? "" : $" [{ExplicitType}]")}> ({Children.Count} children)";
}

/// <summary>
/// A parsed save document, with XStream reference resolution.
/// </summary>
public sealed class SaveDocument
{
    private readonly Dictionary<XStreamNode, XStreamNode> _resolved = new();

    public required XStreamNode Root { get; init; }

    /// <summary>
    /// XStream emits <c>reference="path"</c> instead of repeating an object that has already been
    /// written — so real saves contain them wherever an object is shared or the graph is cyclic
    /// (<c>GameData.protagonist</c> is also in <c>characters</c>; houses contain rooms that contain
    /// characters).
    ///
    /// <para>The path is <b>relative</b> to the referencing element, uses <c>..</c> to climb, and
    /// indexes siblings with a <b>1-based</b> <c>[n]</c> — verified against a fixture generated by
    /// the real game classes, where the second of two same-class characters is written as
    /// <c>../characters/…Charakter[2]</c>.</para>
    ///
    /// <para>Resolution returns the <b>same node instance</b>, preserving object identity. Without
    /// this a reader would either duplicate shared objects (breaking identity comparisons) or
    /// recurse forever on a cycle.</para>
    /// </summary>
    public XStreamNode Resolve(XStreamNode referencing)
    {
        if (!referencing.IsReference)
        {
            return referencing;
        }

        if (_resolved.TryGetValue(referencing, out var cached))
        {
            return cached;
        }

        var target = Walk(referencing, referencing.ReferencePath!);
        _resolved[referencing] = target;
        return target;
    }

    private static XStreamNode Walk(XStreamNode from, string path)
    {
        // Start at the referencing element, then process each segment.
        var current = from;

        foreach (var rawSegment in path.Split('/'))
        {
            var segment = rawSegment;
            if (segment.Length == 0)
            {
                continue;
            }

            if (segment == "..")
            {
                current = current.Parent
                    ?? throw new InvalidDataException(
                        $"reference '{path}' climbed above the document root");
                continue;
            }

            // Optional 1-based index predicate: name[n]
            int? index = null;
            var bracket = segment.IndexOf('[');
            if (bracket >= 0 && segment.EndsWith("]"))
            {
                var digits = segment[(bracket + 1)..^1];
                if (!int.TryParse(digits, out var parsed))
                {
                    throw new InvalidDataException(
                        $"reference '{path}' has a non-numeric index '{digits}'");
                }
                index = parsed;
                segment = segment[..bracket];
            }

            var matches = current.Children.Where(c => c.Name == segment).ToList();
            if (matches.Count == 0)
            {
                throw new InvalidDataException(
                    $"reference '{path}': no child named '{segment}' under <{current.Name}>");
            }

            if (index is null)
            {
                current = matches[0];
            }
            else
            {
                // XStream indexes from 1.
                if (index < 1 || index > matches.Count)
                {
                    throw new InvalidDataException(
                        $"reference '{path}': index [{index}] out of range " +
                        $"(found {matches.Count} '{segment}' siblings)");
                }
                current = matches[index.Value - 1];
            }
        }

        return current;
    }

    /// <summary>Every node in the document, depth-first.</summary>
    public IEnumerable<XStreamNode> AllNodes()
    {
        var stack = new Stack<XStreamNode>();
        stack.Push(Root);
        while (stack.Count > 0)
        {
            var n = stack.Pop();
            yield return n;
            for (var i = n.Children.Count - 1; i >= 0; i--)
            {
                stack.Push(n.Children[i]);
            }
        }
    }
}

/// <summary>Reads XStream-serialised save files.</summary>
public static class SaveFileReader
{
    /// <summary>Parse a save document into a node tree.</summary>
    public static SaveDocument Parse(string xml)
    {
        var doc = XDocument.Parse(xml);
        var root = Convert(doc.Root!, null);
        return new SaveDocument { Root = root };
    }

    private static XStreamNode Convert(XElement el, XStreamNode? parent)
    {
        var node = new XStreamNode { Name = el.Name.LocalName, Parent = parent };

        foreach (var a in el.Attributes())
        {
            node.Attributes[a.Name.LocalName] = a.Value;
        }

        var childElements = el.Elements().ToList();
        if (childElements.Count == 0)
        {
            // XStream writes "" for an empty string and omits the element for null; an element
            // present with no children and no text is an empty collection or a null field.
            var raw = el.Value;
            node.Text = raw.Length == 0 ? "" : raw;
        }
        else
        {
            foreach (var c in childElements)
            {
                node.Children.Add(Convert(c, node));
            }
        }

        return node;
    }

    /// <summary>
    /// The expected root element name for a save file.
    /// </summary>
    /// <remarks>
    /// Verified against a fixture generated by the real game classes: XStream writes the
    /// <b>fully-qualified Java class name</b>, not the <c>@XmlRootElement(name = "gamedata")</c>
    /// value — that JAXB annotation is simply ignored by XStream. Any reader that looks for
    /// <c>&lt;gamedata&gt;</c> will never match a real save.
    /// </remarks>
    public const string GameDataRootElement = "jasbro.game.GameData";
}
