"""Generate C# enum declarations from the Java enums, to avoid transcription errors.

Usage: python gen_enums.py <source_root> <out_file>
"""
import os
import re
import sys

ROOT = sys.argv[1]
OUT = sys.argv[2]

# simple class name -> C# enum name (same unless noted)
WANTED = [
    ("CharacterType", "CharacterType"),
    ("Gender", "Gender"),
    ("SpecializationType", "SpecializationType"),
    ("Sextype", "Sextype"),
    ("ImageTag", "ImageTag"),
    ("Trait", "Trait"),
]


def enum_body(text, name):
    m = re.search(r'\benum\s+' + re.escape(name) + r'\b', text)
    if not m:
        return None
    b = text.index("{", m.end())
    depth, i = 0, b
    while i < len(text):
        if text[i] == "{":
            depth += 1
        elif text[i] == "}":
            depth -= 1
            if depth == 0:
                return text[b + 1:i]
        i += 1
    return None


def split_top_level(body):
    parts, cur, depth = [], [], 0
    for ch in body:
        if ch in "({[":
            depth += 1
        elif ch in ")}]":
            depth -= 1
        if ch == "," and depth == 0:
            parts.append("".join(cur)); cur = []
        elif ch == ";" and depth == 0:
            parts.append("".join(cur)); break
        else:
            cur.append(ch)
    if "".join(cur).strip():
        parts.append("".join(cur))
    return parts


def constants(text, name):
    body = enum_body(text, name)
    if body is None:
        return None
    out = []
    for decl in split_top_level(body):
        m = re.match(r'\s*([A-Za-z_$][A-Za-z0-9_$]*)', decl)
        if m:
            out.append(m.group(1))
    return out


index = {}
for r, _, fs in os.walk(ROOT):
    for f in fs:
        if f.endswith(".java"):
            index[f[:-5]] = os.path.join(r, f)

blocks = []
counts = []
for java_name, cs_name in WANTED:
    p = index.get(java_name)
    if not p:
        print(f"WARNING: {java_name} not found")
        continue
    cs = constants(open(p, encoding="utf-8", errors="replace").read(), java_name)
    if not cs:
        print(f"WARNING: no constants for {java_name}")
        continue
    seen, uniq = set(), []
    for c in cs:
        if c not in seen:
            seen.add(c); uniq.append(c)
    counts.append((cs_name, len(uniq)))
    lines = [f"/// <summary>Legacy <c>{java_name}</c> — {len(uniq)} values.</summary>",
             f"public enum {cs_name}", "{"]
    lines += [f"    {c}," for c in uniq]
    lines += ["}", ""]
    blocks.append("\n".join(lines))

header = """// <auto-generated>
//   Generated from the decompiled Java enums by tools/gen_enums.py.
//   Do not edit by hand — regenerate instead, so the port cannot drift from
//   the shipped game's constant set.
//
//   These names are part of the content and save contract: content XML
//   references them as bare strings, and XStream stores enum names.
// </auto-generated>

namespace Simbro.Core.Content;
"""

os.makedirs(os.path.dirname(OUT), exist_ok=True)
with open(OUT, "w", encoding="utf-8") as fh:
    fh.write(header + "\n" + "\n".join(blocks))

print("generated:", OUT)
for n, c in counts:
    print(f"  {n}: {c} values")
